[package]
name = "microgpu-pico-fw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rp-pico = "0.7"
embedded-hal = "0.2"
panic-halt = "0.2"
cortex-m-rt = "0.7.3"
cortex-m = "0.7.7"